@baseUrl = http://localhost:5209

### Health check
GET {{baseUrl}}/api/health

### Tüm task'lar
GET {{baseUrl}}/api/tasks

### Tek task
GET {{baseUrl}}/api/tasks/1

### Olmayan task
GET {{baseUrl}}/api/tasks/999

### Sayı olmayan id
GET {{baseUrl}}/api/tasks/abc


### Yeni task
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{
  "title": "Profil pages"
}

### Boş başlık (400 beklenir)
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{
  "title": ""
}

### Güncelle
PUT {{baseUrl}}/api/tasks/1
Content-Type: application/json

{
  "title": "Login sayfası (güncellendi)",
  "status": "IN_PROGRESS"
}

### Geçersiz status (400 beklenir)
PUT {{baseUrl}}/api/tasks/1
Content-Type: application/json

{
  "title": "Login",
  "status": "BITTI"
}

### Sil
DELETE {{baseUrl}}/api/tasks/2

### Silineni tekrar sil (404 beklenir)
DELETE {{baseUrl}}/api/tasks/2